[logger]
level = "error"

[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
maxUploadSize = 1000
enableCORS = false
enableXsrfProtection = false
